### ISSUE TITLE
Enable Travis CI Tests

### ISSUE THREAD

**Issue by amilajack** [moesalih/node-eztv#11]
@moesalih I don't have permission to enable travis ci tests. Would be great if you could do this! Thanks.

**Comment by moesalih** [comment]
@amilajack Can I somehow give you permission to set this up?

**Comment by moesalih** [comment]
@amilajack Actually, I've enabled it myself. You can add the .travis.yml file and it should all works.

**Comment by amilajack** [comment]
Great! I've just added the initial travis ci configuration. Also may I also have npm publishing permission?

**Comment by moesalih** [comment]
@amilajack I already gave you npm permissions a while ago.

**Comment by amilajack** [comment]
Oh my bad 😆 been a while since i contributed to this project.
