### ISSUE TITLE
status not being filled

### ISSUE THREAD

**Issue by konsumer** [moesalih/node-eztv#2]
in 0.0.6, status property is being set to undefined.

``` javascript
var eztv = require('eztv');
eztv.getShows({}, function(err, results) {
    if (err) throw err;
    console.log(results);
});
```

and I get lots of records like this:

``` javascript
{
   url: '/shows/798/vikings-us/',
    id: 798,
    slug: 'vikings-us',
    title: 'Vikings (US)',
    status: undefined
}
```

**Comment by konsumer** [comment]
I think npm needs a publish.

**Comment by moesalih** [comment]
Just published 0.0.8

**Comment by theroich** [comment]
node-eztv doesn,t work . it´s been working for several weeks but i don´t know if it´s a problem of my network or do you know if there is any new issue with this module?

**Comment by moesalih** [comment]
The eztv website has been going through a lot of downtime and changes lately. So I have to update the library every time that happens. I just pushed a new version that should work for now.
