### ISSUE TITLE
Error getting show episodes

### ISSUE THREAD

**Issue by palla89** [moesalih/node-eztv#5]
Hi! The getShows function works flawlessly, but getShowEpisodes always give me an error: [Error: Error getting show episodes], is the Api changed or am I doing something wrong? I'm simply doing this:

```javascript
eztv.getShowEpisodes({showId:query},function(error, results) {
    console.log(error);
    console.log(results);
})
```

What I'm doing wrong?

**Comment by amilajack** [comment]
@palla89 this api was out of date for a while. It will be getting significnat updates in a few days. I will open this issue if you have problems with this package in the future.
