### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by amilajack** [moesalih/node-eztv#9]
@moesalih Is this project alive? If you don't have time to contribute anymore, I am willing to maintain this project by doing the following:

- resolve issues
- Merge pull requests
- Write tests
- Update the codebase to ES6 from ES5

**Comment by moesalih** [comment]
@amilajack This project is no longer in development as I have no need for it personally anymore. I just gave you push access to the repo. Thanks for helping 👍

**Comment by amilajack** [comment]
@moesalih thanks so much!

**Comment by amilajack** [comment]
Wondering if you can also give me permission for the npm module as well.

**Comment by moesalih** [comment]
Ohh right, same username as GitHub?

**Comment by amilajack** [comment]
yup!
